/**
 * The scenario event registry — the ~45-event library loaded from
 * event-library.json (generated by the question-analysis workflow, with the
 * examiner's legal corrections applied). Read-only lookups over it.
 */

import libraryJson from "./event-library.json";
import type {
  ScenarioEvent,
  ScenarioLibrary,
  ScenarioStatus,
} from "./types";

const library = libraryJson as unknown as ScenarioLibrary;

/** All scenario events, ordered by exam-point coverage (highest first). */
export const SCENARIO_EVENTS: readonly ScenarioEvent[] = [...library.events].sort(
  (a, b) => b.examPointsCovered - a.examPointsCovered,
);

/** Prioritized build roadmap (Phase 1 = cheapest, highest-leverage). */
export const SCENARIO_ROADMAP = library.roadmap;

/** Coverage totals across the whole question bank. */
export const SCENARIO_TOTALS = library.totals;

const byId = new Map(SCENARIO_EVENTS.map((e) => [e.id, e]));

export function getScenarioEvent(id: string): ScenarioEvent | undefined {
  return byId.get(id);
}

export function scenarioEventsByStatus(status: ScenarioStatus): ScenarioEvent[] {
  return SCENARIO_EVENTS.filter((e) => e.status === status);
}

/** Events live in the engine today (or with their core already built). */
export function liveScenarioEvents(): ScenarioEvent[] {
  return SCENARIO_EVENTS.filter((e) => e.status === "built" || e.status === "partial");
}
