#!/usr/bin/env node
/**
 * Emit a self-contained repair-wave workflow from a lane JSON.
 *
 * WHY THIS LIVES IN THE REPO RATHER THAN IN A SCRATCHPAD: the generators for
 * rounds 2-9 were written in the session scratchpad and a temp cleanup deleted
 * them mid-programme, taking the workflow harness with them. The loop that runs
 * this audit should not depend on a temp directory surviving.
 *
 *   node tools/audit/make-wave.mjs <lanes.json> <outfile.js> <name> <description>
 *
 * The lane JSON is an array of:
 *   { key, label, owns, brief, critical, total,
 *     file?    — the corpus path whose findings this lane reads
 *     reader?  — "findings" (default) | "unrouted" | "none" }
 *
 * Workflow scripts have no filesystem access, so lanes are EMBEDDED. Everything
 * below the lane array is the harness: the findings reader, the rules every lane
 * gets, the fix→refute pipeline and the gate.
 */
import fs from "node:fs";

const [lanesPath, outPath, name, description] = process.argv.slice(2);
if (!lanesPath || !outPath || !name || !description) {
  console.error("usage: make-wave.mjs <lanes.json> <out.js> <name> <description>");
  process.exit(2);
}
const lanes = JSON.parse(fs.readFileSync(lanesPath, "utf8"));
if (!Array.isArray(lanes) || !lanes.length) throw new Error("lane file is empty");

const q = (s) => JSON.stringify(s);
const totals = {
  findings: lanes.reduce((n, l) => n + (l.total || 0), 0),
  critical: lanes.reduce((n, l) => n + (l.critical || 0), 0),
};

const script = `export const meta = {
  name: ${q(name)},
  description: ${q(description)},
  phases: [{ title: 'Fix' }, { title: 'Refute' }, { title: 'Gate' }],
}

// Generated by tools/audit/make-wave.mjs — edit the lane JSON, not this file.

const FIND = 'E:\\\\AI driver\\\\.audit-frames\\\\findings'
const FRAMES = 'E:\\\\AI driver\\\\.audit-frames\\\\sweep161'

const READ_YOUR_FINDINGS = [
  '── HOW TO GET YOUR FINDINGS ──',
  'Nobody hands them to you; handing them over is how 985 were lost once. Write this',
  'to a file and run it with your file path as argv[2] — once per file you own:',
  '',
  '  const fs=require("fs"); const DIR=String.raw\\\`' + FIND + '\\\`;',
  '  const want=process.argv[2].replace(/\\\\\\\\/g,"/"); const all=[];',
  '  for(const f of fs.readdirSync(DIR)){ if(!f.endsWith(".jsonl")) continue;',
  '    for(const l of fs.readFileSync(DIR+"/"+f,"utf8").split("\\\\n")){ if(!l.trim()) continue;',
  '      try{ const j=JSON.parse(l); j.__src=f; all.push(j); }catch(e){} } }',
  '  // SUPERSESSION (docs/simulation/88_LESSON_AUDIT.md): a lesson re-driven in',
  '  // chunk-redrive.jsonl supersedes its OWN older records.',
  '  const key=j=>j.lesson||j.lessonId||j.scenario||j.id||null;',
  '  const rd=new Set(all.filter(j=>j.__src==="chunk-redrive.jsonl").map(key).filter(Boolean));',
  '  const standing=all.filter(j=>j.__src==="chunk-redrive.jsonl"||!(key(j)&&rd.has(key(j))));',
  '  for(const j of standing)',
  '    if(String(j.suspectFile||"").replace(/\\\\\\\\/g,"/")===want && j.bucket==="BROKEN")',
  '      console.log(JSON.stringify(j,null,1));',
  '',
  'Over the whole corpus this reproduces the ledger exactly: 1,686 standing / 1,012',
  'BROKEN / 318 critical / 138 suspect files. If your count disagrees, your reader is',
  'wrong, not the corpus.',
  '',
  'Each record carries \\\`frame\\\`, an absolute PNG under',
  '  ' + FRAMES + '\\\\<lesson>\\\\<platform>-<mode>\\\\*.png',
  'OPEN the frames your findings cite. A fix written without looking at the frame that',
  'motivated it is a guess, and this project has shipped several.',
].join('\\n')

const UNROUTED_READER = [
  'YOUR FINDINGS ARE THE ONES NOBODY ROUTED — they carry \\\`suspectFile: "unknown"\\\`, so no',
  'wave built by grouping on suspectFile has ever seen them. Same reader as above with',
  'the match changed to \\\`String(j.suspectFile||"")==="unknown"\\\`.',
].join('\\n')

const NO_FINDINGS = [
  '── THERE IS NO FINDINGS FILE FOR THIS LANE ──',
  'It was opened by an ADVERSARIAL REFUTER attacking an earlier round, which is the only',
  'reason anyone knows the defect exists. The brief above IS the evidence, and every',
  'number in it was measured. VERIFY IT YOURSELF before changing anything: a refuter can',
  'be wrong too, and a lane that inherits a wrong premise fixes nothing while reporting',
  'that it did.',
].join('\\n')

const RULES = [
  '',
  '── THE RULES, each bought with a fix that had to be binned here ──',
  '',
  ' - THE FRAME WINS. Every "0 defects" report in this project was an instrument bug and all',
  '   of them lied in the REASSURING direction: a scrollWidth probe blind to vertical clipping;',
  '   a parser anchored on /id:/ matching nested objective ids; a speed probe reading the LIMIT',
  '   SIGN instead of the speedometer; a safe-area probe laying the app out on a phone with no',
  '   notch. Any probe you write must self-check against a case verified by eye and exit',
  '   non-zero when it misses it.',
  '',
  ' - A FALSE REFUSAL IS AS BAD AS A FALSE CERTIFICATE. The founder was failed for a roundabout',
  '   exit he signalled correctly; a green tick for a skill nothing measured is the same crime',
  '   pointing the other way, and it puts a seventeen-year-old on a real road believing',
  '   something wrong was right. Prove BOTH directions, always.',
  '',
  ' - A TEST THAT PASSES EQUALLY BEFORE AND AFTER GUARDS NOTHING. Prove every assertion by',
  '   MUTATION: construct the input that SHOULD break it and watch it break. Eight tests here',
  '   were found asserting against comment-stripped SOURCE TEXT; killing the code they guarded',
  '   left 867 tests green.',
  '',
  ' - CREDIT IS READ OFF THE DEBRIEF. Never the task chip — it goes 2/2 → null on session end',
  '   whether or not anything ticked — and never a toast.',
  '',
  ' - DO NOT FIX A SYMPTOM AND LEAVE THE CAUSE. Match the surrounding comment density and',
  '   record the measurement at the site.',
  '',
  '── VERIFY ──',
  '  cd "E:/AI driver/platform" && npx tsc --noEmit',
  '  cd "E:/AI driver/platform" && npx vitest run --maxWorkers=2 <your paths>',
  'NEVER pipe tsc or vitest through tail/echo/head, and never read a background wrapper\\'s',
  'code — a red suite was reported here as EXIT:0 both ways. --maxWorkers=4 yields phantom',
  'failures on this 8-CPU box; use 2.',
  '',
  'A NAMED FAILURE IS NOT EVIDENCE A TEST RAN. A damaged node_modules once made two expected',
  'red files ABSENT while 52 others collected nothing, and an alarm keyed on "are those two',
  'still red?" answers yes to a file that never loaded.',
  '',
  'To DRIVE a lesson: node tools/mobile/lesson-audit.mjs <out> <lesson> <mobile|pc> <right|wrong>',
  'It REFUSES without KNIJKA_BASE, on purpose — the old default pointed at STAGING and returned',
  'a real verdict for a build that was not yours. Start a server from this tree first.',
  '',
  '── KNOWN RED, NOT YOURS, DO NOT MAKE GREEN ──',
  'content-bank.test.ts (ptp-i-parva-pomosht 31/64 against a 50% floor) and compose.test.ts',
  '(l-accidents-first-aid has no quiz beat) need a HUMAN SIGNATURE. 0 of 1,089 questions are',
  'human-signed while 796 unsigned "approved" rows are served to students today. NEVER flip a',
  'content status field.',
  '',
  '── SCOPE ──',
  'Other lanes run concurrently in other files. Touch ONLY what is named as yours. If a fix',
  'belongs elsewhere, say so precisely — the next round routes it — and do not touch it.',
  '',
  'DO NOT COMMIT. Leave NO scratch or probe files behind: five files whose own headers said',
  '"TEMPORARY — delete after reading" were found committed here, green in CI forever.',
  '',
  'Report findings closed, findings you could NOT close and why, and the mutation that proves',
  'each new assertion is real. "Could not close" is respectable; a silent drop is not.',
].join('\\n')

const LANES = ${JSON.stringify(lanes, null, 2)}

log(${q(name)} + ' — ' + LANES.length + ' lanes · ' + LANES.reduce((n, l) => n + (l.total || 0), 0) +
  ' findings · ' + LANES.reduce((n, l) => n + (l.critical || 0), 0) + ' critical')

phase('Fix')

const results = await pipeline(
  LANES,
  (l) =>
    agent(
      [
        'You are one fix lane in the Книжка.AI driving-simulator audit (branch \\\`scenario-engine\\\`,',
        'repo root E:\\\\AI driver, Next.js app in platform/).',
        '',
        'THE PRODUCT: a Bulgarian driving academy for 17-18-year-olds — 161 browser simulator',
        'lessons on real Sofia street topology, plus a theory side. Every lesson was driven right',
        'and wrong, on an iPhone 16 (WebKit, landscape, real safe-area insets) and on a PC',
        '(Chromium 1440x900), and judged FROM ITS OWN FRAMES rather than from metrics. 16,649',
        'frames; 1,012 BROKEN findings stand across 138 files.',
        '',
        'WHY IT MATTERS, so you choose correctly when the convenient fix and the true fix diverge:',
        'a lesson that hands a seventeen-year-old a green tick for a skill it never measured',
        'teaches them that something they did wrong was right, and then puts them on a real road.',
        'That is the tiebreak.',
        '',
        '── YOUR LANE: ' + l.key + ' ──',
        l.file
          ? 'Close the BROKEN findings routed to ' + l.file +
            ' (' + l.total + ' findings, ' + l.critical + ' critical).'
          : '',
        '',
        'YOU OWN:',
        '              ' + l.owns,
        'and its own __tests__ directory. Nothing else.',
        '',
        l.brief,
        '',
        l.reader === 'none' ? NO_FINDINGS : l.reader === 'unrouted' ? UNROUTED_READER : READ_YOUR_FINDINGS,
        RULES,
      ].join('\\n'),
      { label: 'fix:' + l.label, phase: 'Fix' },
    ).catch((e) => '(THIS LANE DIED: ' + String(e && e.message ? e.message : e).slice(0, 300) + ')'),
  (report, l) =>
    agent(
      [
        'Adversarially attack the ' + l.key + ' lane in the Книжка.AI repo at E:\\\\AI driver.',
        'Try to REFUTE it. Default to NOT FIXED when unsure.',
        '',
        'FILES THE LANE OWNED:',
        '              ' + l.owns,
        '',
        '── THE IMPLEMENTER\\'S REPORT ──',
        typeof report === 'string' && report.indexOf('(THIS LANE DIED') === 0
          ? 'THE IMPLEMENTER DIED before reporting. Establish from git diff whether it changed ' +
            'anything before dying, and whether what it left is coherent or a HALF-APPLIED EDIT. ' +
            'A half-applied fix is worse than none.\\n' + report
          : typeof report === 'string'
            ? report.slice(0, 7000)
            : '(returned nothing — attack the diff itself)',
        '',
        '── HOW TO ATTACK ──',
        'EVERY ROUND OF THIS PROGRAMME HAS CAUGHT ITS OWN IMPLEMENTER. A centroid bound that could',
        'not fail at any angle; a per-body fix inert on the only channel a student drives; an',
        'honest number that deleted the row it made honest; a dead API built, unexported and',
        'unread; a guard deleted by the change it existed to catch; a new never-ending drive inside',
        'the never-ending-drive lane. Assume there is one here.',
        '',
        ' 1. DELETION-IN-DISGUISE, first and hardest. Any red assertion can be made green by',
        '    weakening it. For every assertion the lane touched, CONSTRUCT THE INPUT THAT SHOULD',
        '    BREAK IT and prove it breaks. An assertion nothing can fail is deleted, not fixed.',
        '',
        ' 2. INERTNESS. Disable each added line and watch a test go red — line by line.',
        '',
        ' 3. DID IT DELIVER WHAT IT CLAIMED, ON THE SURFACE THAT MATTERS? Read the stated purpose',
        '    and measure it END TO END. A green suite is not delivery.',
        '',
        ' 4. THE OPPOSITE DIRECTION — the one the lane did not check.',
        '',
        ' 5. THE REFERENCE LESSON, if this lane touched the engine, rules, scoring, staging, the',
        '    world builders or the debrief. sc-zebra-approach: right → ИЗДЪРЖАН, 0 наказателни',
        '    точки, 3★; wrong at ~59 км/ч → НЕИЗДЪРЖАН, 20 точки, «Твърде бързо приближаване» −10',
        '    and «Непропускане на пешеходец» −10. Read it off the DEBRIEF. The harness refuses to',
        '    run without KNIJKA_BASE — either point it at a server from THIS tree and say so, or',
        '    drive the same path in-process and say that is what you did.',
        '',
        ' 6. RUN THE SUITE YOURSELF — never through a pipe, --maxWorkers=2, exit code from $?.',
        '',
        'Report what survives and what does not, with measurements. If the lane weakened a check',
        'rather than fixing a defect, say so in those words.',
      ].join('\\n'),
      { label: 'refute:' + l.label, phase: 'Refute' },
    ).catch((e) => '(REFUTER DIED: ' + String(e && e.message ? e.message : e).slice(0, 300) + ')'),
)

phase('Gate')

const gate = await agent(
  [
    'Gate the whole Книжка.AI tree at E:\\\\AI driver after ' + LANES.length + ' concurrent lanes.',
    '',
    'FOUR GATES, exit codes read DIRECTLY from $?, never piped, never from a background wrapper:',
    '  cd "E:/AI driver/platform" && npx tsc --noEmit',
    '  cd "E:/AI driver/platform" && npx vitest run --maxWorkers=2',
    '  cd "E:/AI driver" && node platform/scripts/validate-content.mjs',
    '  cd "E:/AI driver" && node platform/scripts/tools-tests.mjs',
    'THE FOURTH IS A REAL GATE AND IS GREEN. It was red for the first six rounds — its safe-area',
    'probe laid the app out with no notch, so "every number they publish is about a device nobody',
    'owns" — and it has been green since 1625325. Three consecutive gates had to correct this',
    'brief for still calling it red, which is itself the lesson: a fact pinned into an instruction',
    'goes stale while the instruction stays right. RUN IT; do not assume its result either way.',
    '',
    'BASELINE: run \\\`git log --oneline -1\\\` and measure it yourself rather than trusting a number',
    'in this brief — a stale file count has misled three consecutive rounds. The ONLY acceptable',
    'failures are content-bank.test.ts and compose.test.ts, and BOTH MUST HAVE ACTUALLY RUN: a',
    'damaged node_modules once made them ABSENT while 52 files collected nothing, and an alarm',
    'keyed on "are those two still red?" answers yes to a file that never loaded. If either is',
    'GREEN, a content status field was flipped — say so.',
    '',
    'Classify every other failure: (a) a cross-lane collision — a test failing in a file NO lane',
    'owned, (b) a real defect a new test correctly caught, or (c) a lane that shipped a test file',
    'it never ran. Previous rounds produced all three.',
    '',
    'SWEEP FOR RESIDUE: new untracked probe/scratch/zz- files, and any test file under',
    'platform/src with no expect( in it.',
    '',
    'THEN RECOMPUTE THE LEDGER over .audit-frames/findings/*.jsonl with the supersession rule and',
    'update the OPEN LIST in docs/simulation/88_LESSON_AUDIT.md: standing BROKEN, files opened,',
    'files never opened, and every finding a lane said it could NOT close, with its reason',
    'verbatim. The frozen corpus reconciles to 1,686 / 1,012 / 318 / 138 — if your reader',
    'disagrees, your reader is wrong. Report the coverage split as ever-opened / never-opened /',
    'unopenable-as-filed, and note that OWNED IS NOT OPENED: a file a lane was handed and never',
    'edited reads exactly like one that was worked on.',
    '',
    'DO NOT COMMIT.',
  ].join('\\n'),
  { label: 'gate', phase: 'Gate' },
)

return { lanes: LANES.length, gate, reports: results }
`;

fs.writeFileSync(outPath, script);
console.log(
  `wrote ${outPath} — ${lanes.length} lanes · ${totals.findings} findings · ${totals.critical} critical`,
);
