/**
 * answer_bias.mjs — the permanent guard against a question bank that leaks its
 * own answers (audit 2026-07-24, findings H-1 and H-2).
 *
 * WHY THIS FILE EXISTS AT ALL. Both leaks were found by hand, fixed by hand,
 * and then REGENERATED by the next content wave — twice
 * (`content/audits/predimstvo.audit.json` 2026-07-07 "Main defect fixed:
 * severe answer-position bias", then the identical entry in
 * `content/audits/eko-i-zashtitno-shofirane.audit.json`). A defect that
 * survives its own fix is not a content problem, it is a missing check. So the
 * two statistics live here as pure functions with no I/O, and BOTH validators
 * import them:
 *
 *   tools/theory/verify_drafts.mjs        the founder's review queue (reports)
 *   platform/scripts/validate-content.mjs the CI gate (fails the build)
 *
 * One implementation, so the gate and the report can never disagree.
 *
 * The two leaks, and the statistic that catches each:
 *
 *   position-bias  Where does the correct answer sit? The bank once had
 *                  `dokumenti-i-sanktsii.json` at 37/37 correct-at-(a), and
 *                  45.6% bank-wide against a 25% baseline — a monotone
 *                  a>b>c>d decay, not noise. Practice renders the stored
 *                  option order verbatim, so a student answering "always a"
 *                  drives mastery to 1.0 without learning anything, and the
 *                  readiness number the product sells becomes a lie.
 *                  → Pearson chi-square goodness-of-fit against the exact
 *                    per-question uniform expectation.
 *
 *   length-tell    Is the correct answer the visibly longest one? The bank
 *                  once had the correct option uniquely longest in 76% of
 *                  single-answer questions (25% baseline), mean correct length
 *                  70.4 chars vs 44.0 for distractors. Shuffling positions
 *                  does nothing to a length tell — it travels with the text.
 *                  → conditional permutation test: hold the option LENGTHS
 *                    fixed, ask how often the `correct` flag lands on the
 *                    uniquely longest option.
 *
 * Both are mechanical, O(questions), and assume nothing about Bulgarian text.
 */

// ---------------------------------------------------------------------------
// Significance thresholds — the whole design decision, in one place
// ---------------------------------------------------------------------------

/**
 * A run tests ~16 topic files x 3 statistics, plus the pooled bank. At the
 * conventional alpha = 0.05 that is ~2.5 expected FALSE failures on perfectly
 * healthy content, every single run. A gate that reddens CI on good content
 * gets switched off within a week — which is precisely how this defect
 * regressed twice. So:
 *
 *   ALPHA_BLOCK = 0.001  ~5% family-wise false-alarm rate, i.e. roughly one
 *                        spurious red per 20 clean content runs.
 *   ALPHA_WARN  = 0.01   visible in the review queue long before it blocks,
 *                        so drift is caught while it is still cheap.
 *
 * Power at that bar, on this bank's file sizes (~40 single-answer questions
 * per topic): the position gate trips at roughly 50% concentration on one
 * option, and the length gate at roughly 47% longest-correct. Every historical
 * regression sat far above both (100%, 92%, 87%, 80%, 72% at (a); 76% longest
 * bank-wide), so nothing that has ever actually happened would slip through —
 * while a clean seeded shuffle, which lands a couple of questions off uniform
 * by luck, never trips it. The pooled bank-wide test (n ~ 700) is the backstop
 * for the opposite failure mode: a mild bias spread evenly across all 16 files,
 * where no single file is damning but the bank as a whole is.
 */
export const ALPHA_BLOCK = 0.001;
export const ALPHA_WARN = 0.01;

/**
 * Pearson chi-square wants an expected count of >= 5 in every cell; with the
 * bank's 4-option questions that is n >= 20. Below it the statistic is not
 * trustworthy, so a small file is REPORTED and never gated — silence would be
 * worse, a file of 8 questions all answering (a) still deserves a human's eye.
 */
export const MIN_N_FOR_GATE = 20;

/** Scope name of the pooled whole-bank pass, distinct from any topic slug. */
export const POOLED_SCOPE = "__bank__";

// ---------------------------------------------------------------------------
// Statistics (no dependencies — this repo ships no stats library)
// ---------------------------------------------------------------------------

/** Upper-tail critical values of chi-square, exact for the df we can hit. */
const CHI2_TABLE = {
  0.01: [6.635, 9.21, 11.345, 13.277, 15.086, 16.812, 18.475, 20.09, 21.666],
  0.001: [10.828, 13.816, 16.266, 18.467, 20.515, 22.458, 24.322, 26.124, 27.877],
};

/** One-sided standard-normal critical values for the same two alphas. */
const Z_CRIT = { 0.01: 2.3263, 0.001: 3.0902 };

/**
 * Critical value of chi-square at `df` degrees of freedom. Table lookup for
 * df 1..9 (a question would need 10+ options to exceed that); beyond it the
 * Wilson-Hilferty cube-root approximation, accurate to ~2% and only ever a
 * theoretical branch here.
 */
export function chiSquareCritical(df, alpha) {
  const table = CHI2_TABLE[alpha];
  if (!table) throw new Error(`no critical values tabulated for alpha=${alpha}`);
  if (df >= 1 && df <= table.length) return table[df - 1];
  const z = Z_CRIT[alpha];
  return df * (1 - 2 / (9 * df) + z * Math.sqrt(2 / (9 * df))) ** 3;
}

/** Pearson X^2 = sum (observed - expected)^2 / expected, empty cells skipped. */
export function chiSquare(observed, expected) {
  let x2 = 0;
  for (let i = 0; i < observed.length; i++) {
    if (expected[i] > 0) x2 += (observed[i] - expected[i]) ** 2 / expected[i];
  }
  return x2;
}

/** block > warn > ok, from a statistic and its two critical values. */
function severityFor(statistic, warnAt, blockAt, gated) {
  if (!gated) return statistic >= warnAt ? "warn" : "ok";
  if (statistic >= blockAt) return "block";
  return statistic >= warnAt ? "warn" : "ok";
}

// ---------------------------------------------------------------------------
// Position bias
// ---------------------------------------------------------------------------

/**
 * The three answer-position populations a test-wise student can exploit. Each
 * is "which slot holds the odd one out", so each has the same uniform null.
 *
 * `lone-distractor` matters as much as `correct` does: the bank's 4-option /
 * 3-correct multis had their single WRONG option at (d) in 53.8% of cases, and
 * on a multi the exam scores exact-set matching — so "tick everything but the
 * last one" is a complete answering strategy if that bias is left alone.
 */
const POPULATIONS = [
  {
    kind: "single-correct",
    labelBg: "верният отговор при въпрос с един верен",
    /** Index of the one correct option, or -1 when this question is not in scope. */
    index: (q) => (q.type === "single" ? indexOfSole(q.options, true) : -1),
  },
  {
    kind: "multi-lone-distractor",
    labelBg: "единственият грешен отговор при въпрос с няколко верни",
    index: (q) => (q.type === "multi" ? indexOfSole(q.options, false) : -1),
  },
];
// Deliberately NOT a third population: "where does the FIRST correct option
// sit on a multi". Its null is not uniform — with 3 correct of 4 the first one
// lands on (a) three times out of four by arithmetic alone, so a uniform
// chi-square would fail perfectly shuffled content. Only "which slot holds the
// odd one out" has a uniform null, and only those two are tested.

/** Index of the only option matching `correct`, or -1 when there isn't exactly one. */
function indexOfSole(options, correct) {
  let found = -1;
  for (let i = 0; i < options.length; i++) {
    if ((options[i].correct === true) !== correct) continue;
    if (found !== -1) return -1;
    found = i;
  }
  return found;
}

/**
 * Tally one population over a list of questions.
 *
 * The expectation is built per question rather than as `n / k`: a file mixing
 * 3-option and 4-option questions cannot have a correct answer at (d) in the
 * 3-option ones, so a flat n/4 would invent a deficit at (d) out of nothing and
 * fail honest content.
 */
export function tallyPositions(questions, population) {
  const observed = [];
  const expected = [];
  let n = 0;
  for (const q of questions) {
    const options = Array.isArray(q?.options) ? q.options : [];
    if (options.length < 2) continue;
    const index = population.index(q);
    if (index < 0) continue;
    n += 1;
    while (observed.length < options.length) {
      observed.push(0);
      expected.push(0);
    }
    observed[index] += 1;
    for (let i = 0; i < options.length; i++) expected[i] += 1 / options.length;
  }
  return { observed, expected, n };
}

/**
 * Position-bias finding for one population. `df = k - 1` where k is the widest
 * option count seen — the number of slots a correct answer could have landed in.
 * A lone 5-option question in a file of 4-option ones therefore adds a df on a
 * near-empty cell, which only ever makes the test MORE forgiving; erring that
 * way is the right side to err on for a check that reddens CI.
 */
export function positionBias(questions, population) {
  const { observed, expected, n } = tallyPositions(questions, population);
  const k = observed.length;
  const df = Math.max(1, k - 1);
  const x2 = chiSquare(observed, expected);
  const warnAt = chiSquareCritical(df, ALPHA_WARN);
  const blockAt = chiSquareCritical(df, ALPHA_BLOCK);
  const gated = n >= MIN_N_FOR_GATE;

  // The single most over-represented slot, for a detail line a human can act on.
  let topIndex = 0;
  for (let i = 1; i < k; i++) {
    if (observed[i] - expected[i] > observed[topIndex] - expected[topIndex]) topIndex = i;
  }

  return {
    code: "position-bias",
    kind: population.kind,
    labelBg: population.labelBg,
    n,
    observed,
    expected,
    df,
    chiSquare: x2,
    warnAt,
    blockAt,
    gated,
    severity: n === 0 ? "ok" : severityFor(x2, warnAt, blockAt, gated),
    topSlot: n === 0 ? null : slotLabel(topIndex),
    topSharePct: n === 0 ? 0 : (observed[topIndex] / n) * 100,
  };
}

/** 0 -> "a", 1 -> "b" … matching how a student reads the options on screen. */
export const slotLabel = (i) => String.fromCharCode(97 + i);

// ---------------------------------------------------------------------------
// Length tell
// ---------------------------------------------------------------------------

/**
 * How often is the correct option the visibly longest one?
 *
 * The null is a CONDITIONAL permutation: keep the option texts exactly as
 * authored and ask what happens if the `correct` flag is dropped on a random
 * option. Then P(correct is the unique longest) is 1/k when the question has a
 * unique longest option and exactly 0 when the top two lengths tie — no
 * assumption about how long Bulgarian traffic-law prose "should" be, which is
 * what made the old hand-tuned 2.2x ratio reverse-fitted and blind.
 *
 * Only the UNIQUE longest counts. A tie is not exploitable: a student who
 * always picks the longest option still has to guess between the tied ones, so
 * counting ties as hits (the audit's 81.4% figure) overstates the leak. This
 * measures exactly the deterministic edge, the audit's 76.1% figure.
 *
 * The count is a sum of independent Bernoulli trials with different p, so the
 * variance is sum p(1-p) (Poisson-binomial), not n*p*(1-p).
 */
export function lengthTell(questions) {
  let observed = 0;
  let expected = 0;
  let variance = 0;
  let n = 0;
  let ties = 0;

  for (const q of questions) {
    if (q?.type !== "single") continue;
    const options = Array.isArray(q.options) ? q.options : [];
    if (options.length < 2) continue;
    const correctIndex = options.findIndex((o) => o.correct === true);
    if (correctIndex < 0) continue;
    n += 1;

    const lengths = options.map((o) => String(o.textBg ?? "").length);
    const max = Math.max(...lengths);
    const hasUniqueLongest = lengths.filter((l) => l === max).length === 1;
    const p = hasUniqueLongest ? 1 / options.length : 0;
    expected += p;
    variance += p * (1 - p);
    if (lengths[correctIndex] !== max) continue;
    if (hasUniqueLongest) observed += 1;
    else ties += 1;
  }

  const sd = Math.sqrt(variance);
  const z = sd > 0 ? (observed - expected) / sd : 0;
  const gated = n >= MIN_N_FOR_GATE;

  return {
    code: "length-tell",
    n,
    observed,
    ties,
    expected,
    z,
    warnAt: Z_CRIT[ALPHA_WARN],
    blockAt: Z_CRIT[ALPHA_BLOCK],
    gated,
    severity: n === 0 ? "ok" : severityFor(z, Z_CRIT[ALPHA_WARN], Z_CRIT[ALPHA_BLOCK], gated),
    sharePct: n === 0 ? 0 : (observed / n) * 100,
    expectedSharePct: n === 0 ? 0 : (expected / n) * 100,
  };
}

// ---------------------------------------------------------------------------
// The whole-bank sweep both validators call
// ---------------------------------------------------------------------------

/** One human-readable line per finding — the same text in CI and in doc 65. */
export function describeFinding(finding) {
  if (finding.code === "position-bias") {
    const slots = finding.observed
      .map((count, i) => `${slotLabel(i)}:${count}`)
      .join(" ");
    return (
      `позиционен превес — ${finding.labelBg}: {${slots}} на ${finding.n} въпроса, ` +
      `най-натоварен (${finding.topSlot}) с ${finding.topSharePct.toFixed(1)}% ` +
      `(chi2=${finding.chiSquare.toFixed(1)}, df=${finding.df}, ` +
      `праг ${finding.blockAt.toFixed(1)}) — ученик, който винаги избира (${finding.topSlot}), ` +
      "печели точки без да знае правилото"
    );
  }
  return (
    `дължината издава отговора: верният е най-дългият в ${finding.observed}/${finding.n} ` +
    `въпроса (${finding.sharePct.toFixed(1)}%), очаквано ${finding.expectedSharePct.toFixed(1)}% ` +
    `при случайност (z=${finding.z.toFixed(2)}, праг ${finding.blockAt.toFixed(2)}) — ` +
    "разсейващите отговори трябва да са със същата дължина като верния"
  );
}

/**
 * Run both checks over every question file plus the pooled bank.
 *
 * @param {Map<string, object[]>|Iterable<[string, object[]]>} questionsByFile
 * @returns {{ findings: Array, blocking: Array, warnings: Array }}
 *   `findings` carries every population (severity "ok" included) so a report
 *   can show the healthy files too — proof the check ran, not just that it
 *   stayed quiet.
 */
export function analyzeAnswerBias(questionsByFile) {
  const entries = [...questionsByFile];
  const findings = [];

  const scan = (scope, questions) => {
    for (const population of POPULATIONS) {
      findings.push({ scope, ...positionBias(questions, population) });
    }
    findings.push({ scope, ...lengthTell(questions) });
  };

  for (const [scope, questions] of entries) scan(scope, questions ?? []);
  // The pooled pass: 16 files each 8 points above uniform is invisible per
  // file and unmistakable across the bank.
  scan(POOLED_SCOPE, entries.flatMap(([, questions]) => questions ?? []));

  return {
    findings,
    blocking: findings.filter((f) => f.severity === "block"),
    warnings: findings.filter((f) => f.severity === "warn"),
  };
}
