import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Audit M-21. `public/` is static payload, not source: vendored WASM
    // transcoders (basis/, draco/) shipped byte-for-byte by upstream, plus
    // generated media. Linting them produced 513 of the 653 reported problems
    // — none of them ours, none of them fixable without forking a decoder —
    // which buried the ~49 real errors in our own `src/`. Nothing here is
    // authored or maintained in this repo, so nothing here is lintable.
    "public/**",
    // Prisma's generated client. Regenerated by `prisma generate`; any lint
    // fix here is overwritten on the next migration.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
