import type { MetadataRoute } from "next";

/**
 * PWA web app manifest (served at /manifest.webmanifest, auto-linked by Next).
 *
 * WHAT THIS IS ACTUALLY BUYING, AND WHAT IT IS NOT.
 *
 * The founder measured his own iPhone 16 in landscape: Safari's chrome — URL
 * bar, tab strip, share row — is ~19% of the screen height before the road gets
 * a single pixel, and on iOS the Fullscreen API does not exist for non-video
 * elements, so no amount of CSS or JS inside a browser tab can take it back.
 * Installing to the Home Screen and running in `display: standalone` is the
 * ONLY mechanism that removes it. That is the cheapest 19% available anywhere
 * in this product, and this file is what makes it possible.
 *
 * It is the same browser engine running the same code. It is not faster, the
 * physics does not improve, and nothing here is smaller to download. Screen
 * area and a home-screen icon — that is the whole of it, and the in-app copy
 * (components/pwa/InstallHint.tsx) says exactly that.
 *
 * Icons + launch images are generated by `node scripts/generate-icons.mjs` —
 * never edit the PNGs by hand. src/lib/pwa/pwa.test.ts fails if anything
 * declared here is missing from public/ or is not the size it claims.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Книжка.AI — теория, изпити и симулатор",
    short_name: "Книжка.AI",
    description:
      "AI академия за шофьорския изпит в България — адаптивна теория, пробни изпити в официалния формат и AI учител, който цитира закона.",
    id: "/",
    // The dashboard, not the landing page: someone who installed the app has
    // already been sold. An unauthenticated launch round-trips through /login
    // and lands back here (see proxy.ts).
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    // `minimal-ui` before `browser` so a browser that cannot do standalone
    // still drops most of the chrome instead of falling all the way back to a
    // normal tab. `fullscreen` is deliberately NOT first: it would hide the
    // status bar on every screen including the theory reader, and a student
    // studying for an exam should be able to see the clock and their battery.
    // The simulator asks for real fullscreen itself, where it is warranted.
    display_override: ["standalone", "minimal-ui", "browser"],
    // NO ORIENTATION LOCK, stated explicitly rather than left to the default:
    // theory and exams are read in portrait, the simulator wants landscape, and
    // locking either one would break the other. The product spans both.
    orientation: "any",
    // #05070c is the cluster ground (globals.css §CLUSTER) and the same value
    // layout.tsx pins `theme-color` to, so the launch plate, the OS chrome and
    // the first painted frame are one colour with no seam between them.
    background_color: "#05070c",
    theme_color: "#05070c",
    lang: "bg",
    dir: "ltr",
    categories: ["education"],
    // Reuse the window that is already open instead of stacking a second one.
    launch_handler: { client_mode: "navigate-existing" },
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable is not optional on Android: without it the launcher pastes the
      // square mark into its own shape and clips the К's corners. These have the
      // glyph pulled into the inner-80% safe zone.
      {
        src: "/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      { src: "/icons/icon.svg", sizes: "any", type: "image/svg+xml" },
    ],
    // The richer Android install dialog shows these instead of a bare URL. One
    // wide plate only: there is no narrow (phone-shaped) screenshot because
    // fabricating one is worse than not having it, and the wide card already
    // carries the product's claim.
    screenshots: [
      {
        src: "/og.png",
        sizes: "1200x630",
        type: "image/png",
        form_factor: "wide",
        label: "Книжка.AI — адаптивна теория, пробни изпити и симулатор",
      },
    ],
    // Long-press the home-screen icon. Three destinations, one per pillar —
    // the same three the sidebar leads with, so nothing new has to be learned.
    shortcuts: [
      {
        name: "Учи теория",
        short_name: "Теория",
        description: "Адаптивна практика с обяснение защо отговорът е верен.",
        url: "/theory",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Пробен изпит",
        short_name: "Изпит",
        description: "45 въпроса, 97 точки, 40 минути — официалният формат.",
        url: "/exams",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Симулатор",
        short_name: "Кормуване",
        description: "Кабината, по улици на София.",
        url: "/simulator",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
    ],
  };
}
