import type { MetadataRoute } from "next";

/**
 * PWA web app manifest (served at /manifest.webmanifest, auto-linked by Next).
 *
 * Installability requires: this manifest + 192/512 icons + https (or
 * localhost). No service worker in v1 — Chrome no longer requires one for
 * install, and offline support is deliberately post-launch (docs/development/54).
 *
 * Icons are generated by `node scripts/generate-icons.mjs` — never edit the
 * PNGs by hand.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Книжка.AI",
    short_name: "Книжка.AI",
    description:
      "AI академия за шофьорския изпит в България — адаптивна теория, пробни изпити в официалния формат и AI учител, който цитира закона.",
    id: "/",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    // No `orientation` lock: theory is portrait, the simulator wants landscape.
    background_color: "#0a101e",
    theme_color: "#0a101e",
    lang: "bg",
    dir: "ltr",
    categories: ["education"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      { src: "/icons/icon.svg", sizes: "any", type: "image/svg+xml" },
    ],
  };
}
