import type { MetadataRoute } from "next";

/**
 * robots.txt (served at /robots.txt, generated by Next).
 *
 * Public marketing/auth pages are crawlable; everything behind login and the
 * API are not. No sitemap yet — add app/sitemap.ts once there is more than
 * one public page worth indexing.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/dashboard",
          "/theory",
          "/exams",
          "/simulator",
          "/tutor",
          "/pricing",
          "/onboarding",
          "/settings",
        ],
      },
    ],
  };
}
