/**
 * progress.ts — THE SHUT RUNG EXPLAINS ITSELF, AND WITH THE RULE THAT IS
 * ACTUALLY APPLIED.
 *
 * SWEEP161 ROUTING, RE-VERIFIED 2026-08-24 (three independent ways, so the next
 * reader does not spend a round hunting a frame that does not exist):
 *   1. none of the 515 per-drive `*.log` files under `.audit-frames/sweep161/**`
 *      contains „Отключва се", „Заключено ниво", „Избор на ниво" or
 *      `LEVEL_LOCKED` — the level picker was never opened in the whole sweep;
 *   2. every drive in it is `<template>@L1` — the debrief line reads „· Ниво 1
 *      — Пълна помощ · резултат" on all 23 of this file's lessons, and „Ниво 2"
 *      appears only as the end-screen „СЛЕДВАЩО НИВО" CTA. L1 is unconditionally
 *      open here (`unlockedBy: "first"`), so this gate cannot have fired at all;
 *   3. the „+150 XP mobile / +100 XP pc" half of the part-F chunk was already
 *      enumerated and refuted in `lessons/__tests__/progression-sweep161-xp
 *      .test.ts` — one first-pass milestone, not a platform.
 * The 23 findings standing against this file are verdict / XP / briefing /
 * mobile-drive findings. The defect gated below was found by reading this fold
 * against the screen that quotes it, and it is filed as such.
 *
 * THE DEFECT. B9 (doc 86 §3) changed what opens a rung — an ATTEMPT, not two
 * stars — and this fold told nobody. It emits `unlockedBy` for an OPEN rung and
 * bare `null` for a SHUT one, so the picker had no requirement to print and
 * wrote its own, which still says:
 *
 *   ScenarioCatalog.tsx:113  „следващото ниво се отключва с ≥ 2★."
 *   ScenarioCatalog.tsx:226  „Отключва се с ≥ 2★ на предишното ниво"
 *
 * Both are false against this module, and `it("the picker's sentence is not the
 * rule…")` below is that contradiction in one assertion: one 1★ attempt — below
 * the star bar the copy names — opens the next rung, in the fold AND in the save
 * gate. The student who takes 1★ is told he needs stars he does not need, which
 * is the wall FR-06/FR-23 were filed about rebuilt in copy after the engine
 * stopped enforcing it; the student on a genuinely shut rung is pointed at a
 * star target that opens nothing, when what he has to do is drive the rung below
 * once. Doc 64 THEO-4 — an explanation that is not the reason is the defect,
 * not the fix.
 *
 * WHAT THESE TESTS ARE FOR. Not that a string exists — that the string is
 * GENERATED BY THE GATE. Each one below was watched red against a deliberate
 * mutation of the fix, named at the test:
 *   · sentence suppressed (`lockedByBg` always null) → 1, 2, 3, 5, 7 red;
 *   · sentence keyed to `rung.level` instead of the previous rung → 2, 5, 7 red;
 *   · the old „Отключва се с ≥ 2★…" copy returned verbatim → 1, 2, 5 red;
 *   · `prevLevel` taken as `rung.level - 1` arithmetic → 5 red, and ONLY 5:
 *     every shipped ladder is contiguous, so nothing else can see it;
 *   · emitted on OPEN rungs instead of shut ones → 1, 2, 3, 4, 5, 7 and the
 *     admin test red;
 *   · SCENARIO_UNLOCK_MIN_STARS 2 → 1 → 4 and 6 red; 2 → 3 → 6 and the
 *     „previously pinned verdict" test red (the constant guard: round 1 shipped
 *     a threshold that could be set to zero with 798 tests green, and this file
 *     must not let that number move quietly in either direction).
 *
 * NOTHING IS TAKEN AWAY: the last describe() re-pins every field the fold
 * already shipped, on the same rows the two existing suites use, so the new
 * field cannot have moved a verdict.
 */

import { describe, expect, it } from "vitest";
import {
  SCENARIO_UNLOCK_MIN_STARS,
  isScenarioLevelUnlocked,
  scenarioLevelProgress,
  scenarioLockRequirementBg,
  type ScenarioAttemptRow,
} from "../progress";
import { SCENARIO_TEMPLATES, SC_PARK_PERP_REV } from "../templates";
import type { ScenarioLevel } from "../types";

const row = (level: number, stars: number | null): ScenarioAttemptRow => ({
  lessonId: `sc-park-perp-rev@L${level}`,
  rubricStars: stars,
});

/** The rung number the sentence tells the student to go and drive. */
function rungNamedIn(sentence: string): number | null {
  const m = /Ниво\s+(\d+)/.exec(sentence);
  return m === null ? null : Number(m[1]);
}

describe("a shut rung says what actually opens it", () => {
  it("1 · the requirement is a DRIVE, and never a star count", () => {
    // MUTATION WATCHED RED: return the old picker copy „Отключва се с ≥ 2★ на
    // предишното ниво" — every assertion below fails on it.
    const shut = scenarioLevelProgress(SC_PARK_PERP_REV, []).filter((l) => !l.unlocked);
    expect(shut.map((l) => l.level)).toEqual([2, 3, 4, 5]);

    for (const rung of shut) {
      const s = rung.lockedByBg;
      expect(s, `L${rung.level}`).not.toBeNull();
      // Stars open nothing since B9. They must not reappear in this sentence
      // in ANY spelling — the glyph, the word, or the constant's own name.
      expect(s!, `L${rung.level}`).not.toMatch(/★/);
      expect(s!, `L${rung.level}`).not.toMatch(/звезд/i);
      expect(s!, `L${rung.level}`).not.toMatch(/отключва се с/i);
      // …and it has to be actionable: an imperative naming a rung, plus the
      // fact the student is currently being denied — the grade is irrelevant.
      expect(s!, `L${rung.level}`).toMatch(/^Карай Ниво \d+ веднъж/);
      expect(s!, `L${rung.level}`).toMatch(/независимо от оценката/);
    }
  });

  it("2 · it names the rung BELOW this one, not this one", () => {
    // MUTATION WATCHED RED: `scenarioLockRequirementBg(rung.level)` — the
    // off-by-one that would tell a student to drive the very rung he cannot
    // open. Swept over the shipped catalogue, not one template.
    for (const spec of SCENARIO_TEMPLATES) {
      const authored = spec.levels.map((l) => l.level).sort((a, b) => a - b);
      const ladder = scenarioLevelProgress(spec, []);
      for (let i = 0; i < ladder.length; i += 1) {
        const rung = ladder[i];
        if (rung.unlocked) continue;
        expect(rungNamedIn(rung.lockedByBg!), `${spec.id} L${rung.level}`).toBe(
          authored[i - 1],
        );
      }
    }
  });

  it("3 · present exactly when the rung is shut — swept over every template", () => {
    // MUTATION WATCHED RED: emit the sentence on open rungs (drop the
    // `unlockedBy === null` guard) — this fails on L1 of all 167 templates.
    // The pairing is the whole safety property: a picker that renders
    // `lockedByBg` whenever it is present can never caption an open rung, and
    // can never leave a shut one bare.
    let shutSeen = 0;
    let openSeen = 0;
    for (const spec of SCENARIO_TEMPLATES) {
      const authored = spec.levels.map((l) => l.level);
      const rowSets: ScenarioAttemptRow[][] = [[]];
      for (const lvl of authored) {
        for (const stars of [null, 1, 2, 3] as const) {
          rowSets.push([{ lessonId: `${spec.id}@L${lvl}`, rubricStars: stars }]);
        }
      }
      for (const rows of rowSets) {
        for (const opts of [undefined, { unlockAll: true }]) {
          for (const l of scenarioLevelProgress(spec, rows, opts)) {
            const where = `${spec.id} L${l.level} rows=${rows.length} admin=${opts !== undefined}`;
            if (l.unlocked) {
              expect(l.lockedByBg, where).toBeNull();
              openSeen += 1;
            } else {
              expect(l.lockedByBg, where).not.toBeNull();
              shutSeen += 1;
            }
          }
        }
      }
    }
    // Guards the sweep itself: a filter that stopped producing shut rungs would
    // make every assertion above vacuous, and vacuous is how this repo shipped
    // eight green tests over a false claim.
    expect(openSeen).toBeGreaterThan(1000);
    expect(shutSeen).toBeGreaterThan(1000);
  });

  it("4 · the picker's sentence is not the rule — one 1★ attempt opens the rung", () => {
    // THE CONTRADICTION, in one place. ScenarioCatalog.tsx:226 captions a shut
    // rung „Отключва се с ≥ 2★ на предишното ниво". Here is a row set strictly
    // BELOW that bar which opens the rung anyway — in the fold and in the save
    // gate that would otherwise discard the finished drive as LEVEL_LOCKED.
    const oneStar = [row(1, 1)];
    expect(SCENARIO_UNLOCK_MIN_STARS).toBeGreaterThan(1); // the copy's own bar
    const l2 = scenarioLevelProgress(SC_PARK_PERP_REV, oneStar).find((l) => l.level === 2)!;
    expect(l2.unlocked).toBe(true);
    expect(l2.unlockedBy).toBe("attempt");
    expect(l2.lockedByBg).toBeNull();
    expect(isScenarioLevelUnlocked(SC_PARK_PERP_REV, 2, oneStar)).toBe(true);

    // …and an attempt that produced NO stars at all — an aborted session, the
    // «Урокът беше прекъснат преди края» shape the sweep photographed on
    // sc-pk-move-off — is still an attempt. The copy would deny this twice over.
    const aborted = [row(1, null)];
    const l2b = scenarioLevelProgress(SC_PARK_PERP_REV, aborted).find((l) => l.level === 2)!;
    expect(l2b.unlocked).toBe(true);
    expect(l2b.lockedByBg).toBeNull();
    expect(isScenarioLevelUnlocked(SC_PARK_PERP_REV, 2, aborted)).toBe(true);
  });

  it("5 · a gapped ladder is followed by ENTRY, not by arithmetic", () => {
    // MUTATION WATCHED RED: `scenarioLockRequirementBg((rung.level - 1) as …)`.
    // progression.ts:52 measured what arithmetic does to a non-contiguous
    // order list — a rung whose `order - 1` is absent locks forever with no
    // error anywhere. Here the same mistake would print „Карай Ниво 2" for a
    // template that authors no L2, sending the student to a rung the picker
    // cannot even render.
    const gapped = {
      id: "sc-park-perp-rev",
      levels: [
        SC_PARK_PERP_REV.levels[0], // L1
        SC_PARK_PERP_REV.levels[2], // L3
        SC_PARK_PERP_REV.levels[4], // L5
      ],
    };
    expect(gapped.levels.map((l) => l.level)).toEqual([1, 3, 5]);
    const ladder = scenarioLevelProgress(gapped, []);
    expect(ladder.map((l) => l.level)).toEqual([1, 3, 5]);
    expect(ladder[0].lockedByBg).toBeNull();
    expect(rungNamedIn(ladder[1].lockedByBg!)).toBe(1);
    expect(rungNamedIn(ladder[2].lockedByBg!)).toBe(3);
  });

  it("6 · the star bar still decides PASSED, and moving it is not silent", () => {
    // GUARD ON THE CONSTANT, written in LITERALS so it cannot be satisfied by
    // restating SCENARIO_UNLOCK_MIN_STARS. Round 1 shipped a threshold that
    // could be set to zero with 798 tests green; this is the counter to that.
    // MUTATIONS WATCHED RED: 2 → 1 (the 1★ line fails), 2 → 3 (the 2★ line).
    const at = (stars: 1 | 2 | 3) =>
      scenarioLevelProgress(SC_PARK_PERP_REV, [row(1, stars)]).find((l) => l.level === 1)!;
    expect(at(1).passed).toBe(false);
    expect(at(2).passed).toBe(true);
    expect(at(3).passed).toBe(true);
    // …and the bar is a QUALITY bar only: 1★ leaves the rung unpassed and the
    // NEXT one open, which is the whole of B9 in two lines.
    expect(at(1).bestStars).toBe(1);
    expect(
      scenarioLevelProgress(SC_PARK_PERP_REV, [row(1, 1)]).find((l) => l.level === 2)!.unlocked,
    ).toBe(true);
  });

  it("7 · the exported sentence builder is the one the fold uses", () => {
    // The picker will import this to caption any other lock surface; if the
    // fold ever grows a second copy of the wording, this goes red.
    for (const level of [1, 2, 3, 4] as ScenarioLevel[]) {
      const ladder = scenarioLevelProgress(SC_PARK_PERP_REV, []);
      const rung = ladder.find((l) => l.level === level + 1)!;
      expect(rung.lockedByBg).toBe(scenarioLockRequirementBg(level));
    }
  });
});

describe("…and the fold it was added to did not move", () => {
  it("every previously pinned verdict is unchanged", () => {
    // The same row sets the two existing suites use, re-asserted here so this
    // change cannot have shifted a gate while adding a caption to it.
    expect(scenarioLevelProgress(SC_PARK_PERP_REV, []).map((l) => l.unlocked)).toEqual([
      true,
      false,
      false,
      false,
      false,
    ]);
    const twoStars = scenarioLevelProgress(SC_PARK_PERP_REV, [row(1, 2)]);
    expect(twoStars.find((l) => l.level === 2)!.unlockedBy).toBe("stars");
    expect(twoStars.find((l) => l.level === 3)!.unlocked).toBe(false);

    // 2026-08-18, the self-attested rung: still open, still „played", and the
    // rungs under it still shut — that decision is not this change's to make.
    const played = scenarioLevelProgress(SC_PARK_PERP_REV, [row(4, 3)]);
    expect(played.map((l) => [l.level, l.unlocked, l.unlockedBy])).toEqual([
      [1, true, "first"],
      [2, false, null],
      [3, false, null],
      [4, true, "played"],
      [5, true, "stars"], // L4 took 3★, so L5's reason stays the star one
    ]);

    const counted = scenarioLevelProgress(SC_PARK_PERP_REV, [
      row(1, 1),
      row(1, 3),
      row(1, null),
      { lessonId: "l7-parking", rubricStars: 3 },
      { lessonId: "sc-other-template@L1", rubricStars: 3 },
    ]);
    expect(counted.find((l) => l.level === 1)!.attempts).toBe(3);
    expect(counted.find((l) => l.level === 1)!.bestStars).toBe(3);
  });

  it("the admin override still opens every rung, and captions none of them", () => {
    const admin = scenarioLevelProgress(SC_PARK_PERP_REV, [], { unlockAll: true });
    expect(admin.map((l) => l.unlocked)).toEqual([true, true, true, true, true]);
    expect(admin.map((l) => l.lockedByBg)).toEqual([null, null, null, null, null]);
    expect(admin.map((l) => l.unlockedBy)).toEqual([
      "first",
      "admin",
      "admin",
      "admin",
      "admin",
    ]);
  });
});
