/**
 * ov-crossing-v1 („zebra-block" archetype, sc-ov-crossing-overtake) — the
 * district half of a sweep-161 finding, and the routing note for the half that
 * is real.
 *
 * WHY THIS FILE EXISTS AT ALL. `public/world/ov-crossing-v1.json` had no
 * battery of its own, and it is JSON generated by
 * `tools/maps/gen_ov_crossing.mjs` — it can carry neither a comment nor a
 * surviving hand-edit. A finding routed to it therefore had nowhere to be
 * answered, which is how it stayed open and untouched through eleven rounds.
 *
 * THE FINDING (sc-ov-crossing-overtake, mobile-right, major):
 *   „No pedestrian ever appears at the crossing in any of the four runs. The
 *   zebra is painted and the lead car does stop at it, but the briefing's whole
 *   teaching point — «ако предният намалява до пътеката, най-вероятно пропуска
 *   човек, когото ти не виждаш иззад колата му» — has nobody behind the car to
 *   be hidden. The student is taught to infer a person who does not exist."
 *
 * THIS ONE IS NOT REFUTED. The frame
 * (`.audit-frames/sweep161/sc-ov-crossing-overtake/mobile-right/04-t164s.png`)
 * shows exactly what it says: the М8.1 bars are painted across the boulevard,
 * the staged lead car is stopped square on them, the player is crawling at
 * 7 км/ч behind it — and the crossing is EMPTY. The lesson is worse than a
 * missing prop: it trains an inference („slow down, someone you cannot see is
 * crossing") and then never once shows the student that the inference was
 * right. A drill whose payoff never arrives teaches the opposite habit.
 *
 * BUT IT CANNOT BE CLOSED IN THE FILE IT WAS ROUTED TO. A `District` document
 * authors roads, intersections, crossings, roundabouts, buildings, spawnPoints
 * and zones — there is no pedestrian, actor or staged-event field anywhere in
 * the schema, and this district's own contribution (the marked crossing at
 * y = 220) is present and correct, as the assertions below hold. Pedestrians on
 * a scenario map are STAGED ACTORS owned by the lesson template.
 *
 * ROUTED TO, with the exact site:
 *   platform/src/modules/sim/lessons/scenario/templates-lanes.ts
 * where `sc-ov-crossing-overtake` declares `staged: [OVC_LEAD_CAR]` — a single
 * `brakingLeadCar` and nothing else. The teaching point needs a second staged
 * actor: a pedestrian entering the zebra from the far kerb, timed to be MASKED
 * by the lead car from the player's viewpoint and revealed only as the lead
 * pulls away. Until that exists, the briefing line above is a claim the world
 * cannot honour, and the honest interim is to change the words rather than
 * leave the student inferring a ghost.
 *
 * WHAT THIS BATTERY PINS is the district's half — that the zebra the lesson
 * needs is really authored and really painted, so the next round does not
 * re-route the finding back here.
 */
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { buildWorldGeometry } from "../builders/buildWorldGeometry";
import { assertDistrict, type District } from "../types";

const ID = "ov-crossing-v1";
/** The authored zebra's arclength/station on the boulevard, mirrored from the
 *  district file and asserted below rather than trusted. */
const CROSSING_Y = 220;
/** Right-hand lane centre the player spawns and drives in. */
const X_RIGHT = 12.19;

function loadRaw(): unknown {
  const candidates = [
    path.join(process.cwd(), "content", "world", `${ID}.json`),
    path.resolve(process.cwd(), "..", "content", "world", `${ID}.json`),
    path.join(process.cwd(), "public", "world", `${ID}.json`),
  ];
  for (const file of candidates) {
    if (fs.existsSync(file)) return JSON.parse(fs.readFileSync(file, "utf8")) as unknown;
  }
  throw new Error(`${ID}.json not found in: ${candidates.join(", ")}`);
}

const district: District = assertDistrict(loadRaw());

describe(`${ID}: the crossing the lesson is about is authored`, () => {
  it("authors exactly one MARKED, unsignalised crossing, on the boulevard, at y = 220", () => {
    expect(district.crossings).toHaveLength(1);
    const x = district.crossings[0]!;
    expect(x.id).toBe("ovc-x-1");
    expect(x.edgeId).toBe("ovc-e-road");
    expect(x.y).toBe(CROSSING_Y);
    // "marked" is what makes it paint bars at all; an unmarked crossing would
    // give the lead car nothing to stop AT and the drill no referent.
    expect(x.kind).toBe("marked");
    expect(x.signalized).toBe(false);
  });

  it("the player approaches it along a 320 m boulevard, spawning well before it", () => {
    const edge = district.roads.edges.find((e) => e.id === "ovc-e-road")!;
    expect(edge.lanes).toBe(4);
    expect(edge.oneway).toBe(false);
    const spawn = district.spawnPoints.find((s) => s.id === "ovc-spawn-start")!;
    expect(spawn.x).toBe(X_RIGHT);
    expect(spawn.y).toBeLessThan(CROSSING_Y); // the zebra is ahead, not behind
    // …and the map runs on past the crossing, so the drill has a run-out.
    expect(district.meta.boundsLocalMeters.maxY).toBeGreaterThan(CROSSING_Y);
  });

  it("the zebra is actually PAINTED across the carriageway — bars, not just a record", () => {
    // CALIBRATED AGAINST A CONTROL, because the obvious version of this probe
    // passes for free. "Is there marking geometry near y = 220" is TRUE even
    // with the crossing flipped to `unmarked`: the boulevard's longitudinal
    // paint runs through the band. Measured on the shipped map, both ways:
    //
    //            marked            unmarked / plain road at y = 100
    //   verts    124               12
    //   spans    x ∈ [-19.3, 19.3] x ∈ [-8.25, 8.25]
    //
    // So the bars are what makes the band differ FROM THE REST OF THE ROAD, and
    // that difference is what is asserted — a count and a width, each against
    // a control window on the same carriageway.
    const world = buildWorldGeometry(district, { seed: 7 });
    const pos = world.markings.positions;
    const window = (cy: number) => {
      const xs: number[] = [];
      for (let i = 0; i + 2 < pos.length; i += 3) {
        const y = -pos[i + 2]!; // world (x, h, -y) → district y
        if (Math.abs(y - cy) <= 3) xs.push(pos[i]!);
      }
      return xs;
    };
    const zebra = window(CROSSING_Y);
    const control = window(100); // plain stretch of the same boulevard
    expect(control.length).toBeGreaterThan(0); // the control is real paint, not an empty gap
    // Bars put several times more paint in the band than the lines alone do…
    expect(zebra.length).toBeGreaterThan(control.length * 4);
    // …and they reach wider than the longitudinal paint, across BOTH directions.
    const halfWidth = (xs: number[]) => Math.max(Math.max(...xs), -Math.min(...xs));
    expect(halfWidth(zebra)).toBeGreaterThan(halfWidth(control) * 2);
    expect(Math.min(...zebra)).toBeLessThan(0);
    expect(Math.max(...zebra)).toBeGreaterThan(0);
  });
});
