// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
//
// iOS launch images. The device table and the reasoning live in the generator;
// this file exists so app/layout.tsx declares exactly the plates that were
// actually rendered, and so pwa.test.ts can prove the two never drift.

export interface IosSplashPlate {
  /** Public URL of the rendered plate. */
  url: string;
  /** The media query iOS matches the device against — an exact match or nothing. */
  media: string;
  /** Rendered size in device pixels. */
  width: number;
  height: number;
  /** Which phones this plate is for (documentation only). */
  device: string;
}

export const IOS_SPLASH_PLATES: readonly IosSplashPlate[] = [
  {
    "url": "/icons/splash/splash-750x1334.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    "width": 750,
    "height": 1334,
    "device": "iPhone SE (2nd/3rd gen), 8, 7, 6s"
  },
  {
    "url": "/icons/splash/splash-1334x750.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
    "width": 1334,
    "height": 750,
    "device": "iPhone SE (2nd/3rd gen), 8, 7, 6s"
  },
  {
    "url": "/icons/splash/splash-1125x2436.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1125,
    "height": 2436,
    "device": "iPhone X, XS, 11 Pro, 12 mini, 13 mini"
  },
  {
    "url": "/icons/splash/splash-2436x1125.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2436,
    "height": 1125,
    "device": "iPhone X, XS, 11 Pro, 12 mini, 13 mini"
  },
  {
    "url": "/icons/splash/splash-1170x2532.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1170,
    "height": 2532,
    "device": "iPhone 12, 12 Pro, 13, 13 Pro, 14"
  },
  {
    "url": "/icons/splash/splash-2532x1170.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2532,
    "height": 1170,
    "device": "iPhone 12, 12 Pro, 13, 13 Pro, 14"
  },
  {
    "url": "/icons/splash/splash-1179x2556.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1179,
    "height": 2556,
    "device": "iPhone 14 Pro, 15, 15 Pro, 16"
  },
  {
    "url": "/icons/splash/splash-2556x1179.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2556,
    "height": 1179,
    "device": "iPhone 14 Pro, 15, 15 Pro, 16"
  },
  {
    "url": "/icons/splash/splash-1206x2622.png",
    "media": "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1206,
    "height": 2622,
    "device": "iPhone 16 Pro"
  },
  {
    "url": "/icons/splash/splash-2622x1206.png",
    "media": "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2622,
    "height": 1206,
    "device": "iPhone 16 Pro"
  },
  {
    "url": "/icons/splash/splash-828x1792.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
    "width": 828,
    "height": 1792,
    "device": "iPhone XR, 11"
  },
  {
    "url": "/icons/splash/splash-1792x828.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
    "width": 1792,
    "height": 828,
    "device": "iPhone XR, 11"
  },
  {
    "url": "/icons/splash/splash-1284x2778.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1284,
    "height": 2778,
    "device": "iPhone 12 Pro Max, 13 Pro Max, 14 Plus"
  },
  {
    "url": "/icons/splash/splash-2778x1284.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2778,
    "height": 1284,
    "device": "iPhone 12 Pro Max, 13 Pro Max, 14 Plus"
  },
  {
    "url": "/icons/splash/splash-1290x2796.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1290,
    "height": 2796,
    "device": "iPhone 14 Pro Max, 15 Plus, 15 Pro Max, 16 Plus"
  },
  {
    "url": "/icons/splash/splash-2796x1290.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2796,
    "height": 1290,
    "device": "iPhone 14 Pro Max, 15 Plus, 15 Pro Max, 16 Plus"
  },
  {
    "url": "/icons/splash/splash-1320x2868.png",
    "media": "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
    "width": 1320,
    "height": 2868,
    "device": "iPhone 16 Pro Max"
  },
  {
    "url": "/icons/splash/splash-2868x1320.png",
    "media": "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)",
    "width": 2868,
    "height": 1320,
    "device": "iPhone 16 Pro Max"
  }
] as const;
