/**
 * Seed the founder account with role=admin (idempotent).
 *
 * - Account exists  → only User.role is set to "admin" (password untouched).
 * - Fresh/reset DB  → the account is created with a dev password
 *   (SEED_FOUNDER_PASSWORD env, default below — LOCAL DEV ONLY; set the env
 *   var before ever seeding a shared environment).
 *
 * Wired as the prisma seed (prisma.config.ts migrations.seed), so a
 * `prisma migrate reset` / `prisma db seed` keeps the founder admin.
 * Run directly: npm run seed:founder
 */

import "dotenv/config";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { Client } = require("pg");
const { hash } = require("bcryptjs");

const FOUNDER_EMAIL = "founder@knijka.ai";
const FOUNDER_NAME = "Antonio (Founder)";
const DEV_PASSWORD = process.env.SEED_FOUNDER_PASSWORD ?? "founder-dev";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("seed-founder: DATABASE_URL is not set (see .env.example)");
  process.exit(1);
}

const client = new Client({ connectionString });
await client.connect();

try {
  const existing = await client.query(
    'SELECT id, role FROM "User" WHERE email = $1',
    [FOUNDER_EMAIL],
  );

  if (existing.rows.length > 0) {
    const { id, role } = existing.rows[0];
    if (role === "admin") {
      console.log(`seed-founder: ${FOUNDER_EMAIL} (${id}) already admin — nothing to do`);
    } else {
      await client.query('UPDATE "User" SET role = $1 WHERE id = $2', ["admin", id]);
      console.log(`seed-founder: ${FOUNDER_EMAIL} (${id}) role ${role} -> admin`);
    }
  } else {
    // cuid-style id is generated by Prisma normally; a plain unique id is
    // fine for the seeded row (same shape the app already tolerates).
    const id = `founder${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
    const passwordHash = await hash(DEV_PASSWORD, 12);
    await client.query(
      `INSERT INTO "User" (id, email, name, "passwordHash", locale, role, "consentAt", "createdAt")
       VALUES ($1, $2, $3, $4, 'bg', 'admin', NOW(), NOW())`,
      [id, FOUNDER_EMAIL, FOUNDER_NAME, passwordHash],
    );
    console.log(
      `seed-founder: created ${FOUNDER_EMAIL} (${id}) as admin` +
        (process.env.SEED_FOUNDER_PASSWORD ? "" : " with the default dev password"),
    );
  }
} finally {
  await client.end();
}
