/**
 * Seed the founder account with role=admin (idempotent).
 *
 * - Account exists  → only User.role is set to "admin" (password untouched).
 * - Fresh/reset DB  → the account is created with SEED_FOUNDER_PASSWORD.
 *
 * THERE IS NO DEFAULT PASSWORD, AND THAT IS THE POINT. This file used to read
 * `process.env.SEED_FOUNDER_PASSWORD ?? "founder-dev"` — a literal in a PUBLIC
 * repository, on an account created with role=admin. Admin in this product is
 * not a convenience flag: it bypasses the simulator entitlement (the whole
 * EUR 21.99 pack), the mock-exam limit, the practice cap, the hazard gate and
 * the tutor quota. The convenience of one fewer environment variable was
 * therefore a published key to every paywall the product has.
 *
 * Missing or weak SEED_FOUNDER_PASSWORD is now FATAL, and two further refusals
 * (NODE_ENV=production, a non-localhost DATABASE_URL) make it impossible to
 * point this at anything that looks like a live system. All three live in
 * seed-founder-guards.mjs, which is unit-tested — see
 * src/lib/ops/seedFounderGuards.test.ts.
 *
 * Wired as the prisma seed (prisma.config.ts migrations.seed), so a
 * `prisma migrate reset` / `prisma db seed` keeps the founder admin — and now
 * needs SEED_FOUNDER_PASSWORD in .env to do it. CI never runs the seed
 * (`prisma migrate deploy` only), so this cannot break the gate.
 * Run directly: npm run seed:founder
 */

import "dotenv/config";
import { createRequire } from "node:module";
import { checkSeedEnvironment } from "./seed-founder-guards.mjs";

const require = createRequire(import.meta.url);
const { Client } = require("pg");
const { hash } = require("bcryptjs");

const FOUNDER_EMAIL = "founder@knijka.ai";
const FOUNDER_NAME = "Antonio (Founder)";

// BEFORE ANYTHING ELSE, and before any connection is opened: a guard that runs
// after the client connects would report a network error instead of the real
// reason, which is how "it just doesn't work" gets debugged for an hour.
const guard = checkSeedEnvironment(process.env);
if (!guard.ok) {
  console.error(guard.message);
  process.exit(1);
}

const client = new Client({ connectionString: guard.databaseUrl });
await client.connect();

try {
  const existing = await client.query(
    'SELECT id, role FROM "User" WHERE email = $1',
    [FOUNDER_EMAIL],
  );

  if (existing.rows.length > 0) {
    const { id, role } = existing.rows[0];
    if (role === "admin") {
      console.log(`seed-founder: ${FOUNDER_EMAIL} (${id}) already admin — nothing to do`);
    } else {
      await client.query('UPDATE "User" SET role = $1 WHERE id = $2', ["admin", id]);
      console.log(`seed-founder: ${FOUNDER_EMAIL} (${id}) role ${role} -> admin`);
    }
  } else {
    // cuid-style id is generated by Prisma normally; a plain unique id is
    // fine for the seeded row (same shape the app already tolerates).
    const id = `founder${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
    const passwordHash = await hash(guard.password, 12);
    await client.query(
      `INSERT INTO "User" (id, email, name, "passwordHash", locale, role, "consentAt", "createdAt")
       VALUES ($1, $2, $3, $4, 'bg', 'admin', NOW(), NOW())`,
      [id, FOUNDER_EMAIL, FOUNDER_NAME, passwordHash],
    );
    // Never echo the password, not even a prefix: this line ends up in shell
    // history, CI logs and screen recordings.
    console.log(`seed-founder: created ${FOUNDER_EMAIL} (${id}) as admin`);
  }
} finally {
  await client.end();
}
